// design/tokens.json → src/styles/tokens.gen.css. `--check` fails on drift (CI via `bun run tokens:check`).
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { contrast } from "../src/lib/contrast";
export { contrast };

export type Tokens = typeof import("../design/tokens.json");

const kebab = (s: string) => s.replace(/[A-Z]/g, (c) => "-" + c.toLowerCase());

const block = (vars: Record<string, string>, prefix: string) =>
  Object.entries(vars).map(([k, v]) => `  --${prefix}${kebab(k)}: ${v};`).join("\n");

export function gen(t: Tokens): string {
  const base = [
    block(t.semantic.dark, "c-"),
    block(t.ansi, "ansi-"),
    t.space.slice(1).map((v, i) => `  --sp-${i + 1}: ${v}px;`).join("\n"),
    Object.entries(t.radius).map(([k, v]) => `  --r-${k}: ${v}px;`).join("\n"),
    t.type.scale.map((v, i) => `  --fs-${i + 1}: ${v / 16}rem;`).join("\n"),
    Object.entries(t.type.leading).map(([k, v]) => `  --leading-${k}: ${v};`).join("\n"),
    `  --control-height: ${t.control.height}px;\n  --disabled-opacity: ${t.control.disabledOpacity};`,
    Object.entries(t.z).map(([k, v]) => `  --z-${k}: ${v};`).join("\n"),
    `  --ease: ${t.motion.ease};`,
    `  --d-fast: ${t.motion.fast}ms;\n  --d-base: ${t.motion.base}ms;\n  --d-slow: ${t.motion.slow}ms;`,
    `  --font-mono: "JetBrains Mono", "JetBrains Mono Fallback", ui-monospace, "SFMono-Regular", Menlo, monospace;`,
    `  --font-mark: "VT323 Mark", var(--font-mono);`,
    `  --cat-color: ${t.primitive.scene.cat};\n  --cat-edge: ${t.primitive.scene.catEdge};`,
    `  color-scheme: dark;`,
  ].join("\n");
  const light = `${block(t.semantic.light, "c-")}\n  color-scheme: light;`;
  return `/* generated by scripts/gen-tokens.ts from design/tokens.json. Do not edit. */
:root {
${base}
}
:root[data-theme="light"] {
${light}
}
@media (prefers-color-scheme: light) {
  :root:not([data-theme="dark"]) {
${light.replace(/^/gm, "  ")}
  }
}
/* scoped themes: a subtree that always renders dark or light, whatever the page theme (docs previews) */
.mw-theme--dark {
${block(t.semantic.dark, "c-")}
  color-scheme: dark;
}
.mw-theme--light {
${light}
}
`;
}

// Read via a local binding, not the `new URL(literal, import.meta.url)` pattern directly: Vite's
// static asset-URL transform (used when this module is imported through vitest) rewrites that exact
// pattern into a dev-server URL, breaking fileURLToPath. Bun (the real entry point) is unaffected.
const metaUrl = import.meta.url;
const OUT = fileURLToPath(new URL("../src/styles/tokens.gen.css", metaUrl));

if (import.meta.main) {
  const tokens: Tokens = JSON.parse(readFileSync(new URL("../design/tokens.json", metaUrl), "utf8"));
  const css = gen(tokens);
  if (process.argv.includes("--check")) {
    let current = "";
    try { current = readFileSync(OUT, "utf8"); } catch { /* missing = drift */ }
    if (current !== css) {
      console.error("tokens.gen.css is out of date. Run `bun run tokens`.");
      process.exit(1);
    }
  } else {
    writeFileSync(OUT, css);
    console.log("wrote", OUT);
  }
}
